# Imagen base ligera de Python
FROM python:3.10-slim

# Establecer variables de entorno para evitar creación de archivos .pyc y buffers
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Establece el directorio de trabajo
WORKDIR /home/ubuntu/backend

# Copia e instala dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el proyecto completo
COPY . .

# Expón el puerto 8000
EXPOSE 8000

# Establece la variable de entorno para Django
ENV DJANGO_SETTINGS_MODULE=mysite.settings

# Comando de inicio: Gunicorn con 3 workers
CMD ["gunicorn", "mysite.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]