# Generated by Django 5.1.7 on 2025-05-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion',
            field=models.IntegerField(),
        ),
    ]
