# Generated by Django 5.1.9 on 2025-05-27 16:07

import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.FileField(null=True, upload_to=tienda.models.upload_path),
        ),
    ]
