# Generated by Django 5.1.9 on 2025-05-28 16:33

import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to=tienda.models.upload_path),
        ),
    ]
