# Generated by Django 5.1.7 on 2025-05-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_reseña_puntuacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='fecha_creacion',
        ),
    ]
