# Generated by Django 5.1.9 on 2025-05-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_reseña_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='n_pedido',
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
