# Generated by Django 5.1.9 on 2025-05-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='producto',
            new_name='productos',
        ),
    ]
