# Generated by Django 5.1.9 on 2025-06-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_producto_compra_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='dni',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
