# Generated by Django 5.1.9 on 2025-05-19 15:28

import django.db.models.deletion
import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_compra_n_pedido_compra_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='total',
            new_name='totalCompra',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='clientes',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=tienda.models.upload_path),
        ),
        migrations.CreateModel(
            name='ProductoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ManyToManyField(through='tienda.ProductoCompra', to='tienda.producto'),
        ),
    ]
