# Generated by Django 5.1.9 on 2025-06-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_compra_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre_completo',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='telefono',
            field=models.CharField(default=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='compra',
            name='dni',
            field=models.CharField(default=True, max_length=9),
        ),
    ]
