# Generated by Django 5.1.10 on 2025-06-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_usuario_rol_creador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseña',
            new_name='Resena',
        ),
    ]
